// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Geocalc.Data;

#nullable disable

namespace Geocalc.Migrations
{
    [DbContext(typeof(GeoZoneContext))]
    [Migration("20241026023934_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Geocalc.Models.GeoZone", b =>
                {
                    b.Property<int>("GeoZoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Geometry>("Border")
                        .IsRequired()
                        .HasColumnType("GEOMETRY");

                    b.HasKey("GeoZoneID");

                    b.ToTable("GeoZone");
                });
#pragma warning restore 612, 618
        }
    }
}
